// Auto-generated by fetch-gen
import type { FetchClient, FetchResponse } from '@fgrzl/fetch';
import { buildQueryParams } from '@fgrzl/fetch';

/**
 * Creates an API adapter with typed methods for all OpenAPI operations
 * @param client The FetchClient instance to use for HTTP requests
 * @returns An object with typed methods for each API operation
 */
export function createAdapter(client: FetchClient): {
	/**
	 * Detect SSO providers for an email address
	 * @param query Query parameters
	 */
	detectSSOProviders: (query?: { email?: string }) => Promise<FetchResponse<Array<string>>>;
	/**
	 * Get JSON Web Key Set
	 */
	getJWKS: () => Promise<FetchResponse<JWKSResponse>>;
	/**
	 * Handle SSO callback
	 * @param provider provider parameter
	 * @param query Query parameters
	 */
	ssoCallback: (provider: string, query?: { code?: string; state?: string }) => Promise<FetchResponse<boolean>>;
	/**
	 * Initiate SSO login flow
	 * @param provider provider parameter
	 * @param query Query parameters
	 */
	ssoLogin: (provider: string, query?: { email?: string; return_url?: string }) => Promise<FetchResponse<boolean>>;
	/**
	 * Logout user
	 */
	logout: () => Promise<FetchResponse<boolean>>;
	/**
	 * Get current user information
	 */
	getCurrentUser: () => Promise<FetchResponse<UserIdentity>>;
	/**
	 * Get email verification status
	 */
	getVerificationStatus: () => Promise<FetchResponse<EmailVerificationStatus>>;
	/**
	 * Verify email address
	 * @param query Query parameters
	 */
	verifyEmail: (query?: { email?: string; token?: string }) => Promise<FetchResponse<boolean>>;
	/**
	 * Resend verification email
	 */
	resendVerification: () => Promise<FetchResponse<EmailVerificationStatus>>;
} {
	return {
		detectSSOProviders: (query?: { email?: string }): Promise<FetchResponse<Array<string>>> => {
			const queryString = query ? buildQueryParams(query) : '';
			const url = `/api/v1/sso/detect` + (queryString ? '?' + queryString : '');
			return client.get(url);
		},
		getJWKS: (): Promise<FetchResponse<JWKSResponse>> => {
			return client.get(`/auth/.well-known/jwks.json`);
		},
		ssoCallback: (provider: string, query?: { code?: string; state?: string }): Promise<FetchResponse<boolean>> => {
			const queryString = query ? buildQueryParams(query) : '';
			const url = `/auth/callback/${provider}` + (queryString ? '?' + queryString : '');
			return client.get(url);
		},
		ssoLogin: (provider: string, query?: { email?: string; return_url?: string }): Promise<FetchResponse<boolean>> => {
			const queryString = query ? buildQueryParams(query) : '';
			const url = `/auth/login/${provider}` + (queryString ? '?' + queryString : '');
			return client.get(url);
		},
		logout: (): Promise<FetchResponse<boolean>> => {
			return client.get(`/auth/logout`);
		},
		getCurrentUser: (): Promise<FetchResponse<UserIdentity>> => {
			return client.get(`/auth/me`);
		},
		getVerificationStatus: (): Promise<FetchResponse<EmailVerificationStatus>> => {
			return client.get(`/auth/verification-status`);
		},
		verifyEmail: (query?: { email?: string; token?: string }): Promise<FetchResponse<boolean>> => {
			const queryString = query ? buildQueryParams(query) : '';
			const url = `/auth/verify` + (queryString ? '?' + queryString : '');
			return client.get(url);
		},
		resendVerification: (): Promise<FetchResponse<EmailVerificationStatus>> => {
			return client.post(`/auth/verify/resend`);
		}
	};
}

/** EmailVerificationStatus schema */
export interface EmailVerificationStatus {
	email?: string;
	expires_at?: string;
	is_verified?: boolean;
	requested_at?: string;
	user_id?: string;
	verification_url?: string;
}

/** JWKResponse schema */
export interface JWKResponse {
	alg?: string;
	e?: string;
	kty?: string;
	n?: string;
	use?: string;
}

/** JWKSResponse schema */
export interface JWKSResponse {
	keys?: Array<JWKResponse>;
}

/** ProblemDetails schema */
export interface ProblemDetails {
	detail?: string;
	instance?: string;
	status?: number;
	title?: string;
	type?: string;
}

/** UserIdentity schema */
export interface UserIdentity {
	email?: string;
	name?: string;
	user_id?: string;
}

